# Generated by Django 4.2.3 on 2023-07-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='imagess')),
                ('status', models.BooleanField(default=False, help_text='0=defualt,1=Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=defualt,1=Hidden')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
