# Generated by Django 4.2.1 on 2023-08-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_products_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=40)),
                ('messege', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
