# Generated by Django 4.2.1 on 2023-09-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
